"""Crate blending operation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/12_data_processing.blending.ipynb.

# %% auto 0
__all__ = ['CV_TOOLS', 'custom_lib_path', 'CURRETNT_NB']

# %% ../../nbs/12_data_processing.blending.ipynb 3
import sys
from pathlib import Path


# %% ../../nbs/12_data_processing.blending.ipynb 4
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append(str(CV_TOOLS))


# %% ../../nbs/12_data_processing.blending.ipynb 5
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))


# %% ../../nbs/12_data_processing.blending.ipynb 6
from ..imports import *
from ..core import *
from dotenv import load_dotenv


# %% ../../nbs/12_data_processing.blending.ipynb 7
load_dotenv(dotenv_path=f'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools/cv_tools/.env')

# %% ../../nbs/12_data_processing.blending.ipynb 9
CURRETNT_NB='/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools/nbs'
