# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cv_tools',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/cv_tools',
                'lib_path': 'cv_tools'},
  'syms': {'cv_tools.core': {'cv_tools.core.foo': ('core.html#foo', 'cv_tools/core.py')}}}
